#! /usr/bin/env sh

TARGET_URL="http://localhost:3003/"

xset s noblank
xset s off
xset -dpms

matchbox-window-manager -use_titlebar no &

unclutter -idle 0.5 -root &

if [ -d $HOME/.config/chromium ]
then
        sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' $HOME/.config/chromium/Default/Preferences
        sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' $HOME/.config/chromium/Default/Preferences
fi

exec /usr/bin/chromium-browser --noerrdialogs --disable-infobars --kiosk --incognito --window-position=0,0 $TARGET_URL
